INSERT INTO usuarios (nombre, apellidos, email, telefono, password) VALUES('Miguel Alfredo', 'Armas Chávez', 'miguelarmas@gmail.com', '637112233', 'miguelarmas');
INSERT INTO usuarios (nombre, apellidos, email, telefono, password) VALUES('Nicolás', 'Darmanin Casariego', 'nicolasdarmanin@gmail.com', '637223344', 'nicolasdarmanin');
INSERT INTO usuarios (nombre, apellidos, email, telefono, password) VALUES('Rafael Eduardo', 'Delgado Rocca', 'rafaeldelgaado@gmail.com', '637334455', 'rafaeldelgado');
INSERT INTO reserva (fecha, fkusuario, hora) VALUES ('2022/03/15', '1', '12:00:00');
INSERT INTO reserva (fecha, fkusuario, hora) VALUES ('2022/03/15', '2', '12:30:00');
INSERT INTO reserva (fecha, fkusuario, hora) VALUES ('2022/03/15', '3', '13:00:00');
INSERT INTO rol	(rol, descripcion) VALUES ('admin', 'persona que tiene permisos totales');
INSERT INTO rol	(rol, descripcion) VALUES ('cliente', 'persona que tiene permisos limitados');
INSERT INTO rol	(rol, descripcion) VALUES ('peluquero', 'persona que tiene permisos parciales');
INSERT INTO review (estrellas, opiniones, fkusuario) VALUES ('5', 'recomendable, gran profecional', '5');
INSERT INTO review (estrellas, opiniones, fkusuario) VALUES ('3', 'nada profecional', '1');
INSERT INTO review (estrellas, opiniones, fkusuario) VALUES ('5', 'muy amable, gran profecional', '5');
INSERT INTO servicio (servicio, precio, tiempo) VALUES ('corte de pelo', '9.0', '25');
INSERT INTO servicio (servicio, precio, tiempo) VALUES ('corte de pelo + barba', '12.0', '30');
INSERT INTO servicio (servicio, precio, tiempo) VALUES ('barba', '5.0', '5');
INSERT INTO reservaservicio (fkreserva, fkservicio) VALUES ('1', '1');
INSERT INTO reservaservicio (fkreserva, fkservicio) VALUES ('2', '3');
INSERT INTO reservaservicio (fkreserva, fkservicio) VALUES ('3', '2');
INSERT INTO usuariorol (fkusuario, fkrol) VALUES ('1', '1');
INSERT INTO usuariorol (fkusuario, fkrol) VALUES ('2', '2');
INSERT INTO usuariorol (fkusuario, fkrol) VALUES ('3', '3');